---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-registry-strimzi-io-v1alpha1-schema
  failurePolicy: Fail
  name: vschema-v1alpha1.kb.io
  rules:
  - apiGroups:
    - registry.strimzi.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - schemas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-registry-strimzi-io-v1alpha1-schemaregistry
  failurePolicy: Fail
  name: vschemaregistry-v1alpha1.kb.io
  rules:
  - apiGroups:
    - registry.strimzi.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - schemaregistries
  sideEffects: None
