# This rule is not used by the project schema-strimzi-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to registry.strimzi.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: schema-strimzi-operator
    app.kubernetes.io/managed-by: kustomize
  name: schemaregistry-viewer-role
rules:
- apiGroups:
  - registry.strimzi.io
  resources:
  - schemaregistries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - registry.strimzi.io
  resources:
  - schemaregistries/status
  verbs:
  - get
